### PR TITLE
Some minor changes for better UX

### PR DESCRIPTION
**Pull request by Wolterhon**

### CODE REVIEW

**Comment by Ryzhehvost** [comment]
Please, make sure that your PR is based on latest source before sending. Also, from what I see - only usage of `onbeforeunload` is actually new there, and I'm not sure if I really want to use it. 
As for readme - while installing directly from github is obvously possible, I consider installing via https://greasyfork.org/en/scripts/404754-asf-stm default and recommended way.

**Comment by Wolterhon** [comment]
> Please, make sure that your PR is based on latest source before sending.
Alright, terribly sorry.

> is actually new there
Once the ASF public listing was down, so the button wasn't there on the page, which leads to confusion of the end user: is the script even running? There was no need in writing additional code, I just moved the part that creates the button so that it's always on the page, and when the public listing is confirmed to be up the button becomes active.

> and I'm not sure if I really want to use it.
The final decision is on you obviously, but again, there have been multiple times when I (and I'm sure I'm not the only one) accidentally closed the tab where the script was running, so yeah, I felt like this needed to be done.

> I consider installing via
Then maybe put the greasyfork link in the readme file?

**Comment by Ryzhehvost** [comment]
> Once the ASF public listing was down, so the button wasn't there on the page, which leads to confusion of the end user: is the script even running?

That's why I'm saying to base on latest version - this was fixed before your PR.

**Comment by Wolterhon** [comment]
> That's why I'm saying to base on latest version - this was fixed before your PR.

Got you now. What about `onbeforeunload` though? Do you not like the idea itself or the implementation?

**Comment by Ryzhehvost** [comment]
> What about `onbeforeunload` though? Do you not like the idea itself or the implementation?

I'm talking about idea. But haven't decided yet. Will think about it a little bit more.

**Comment by Wolterhon** [comment]
What about the greasyfork link though? Shouldn't it be in the readme?

**Pull request closed without merging**
